import { useEffect, useState, useRef } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area } from 'recharts';
import { Activity, AlertTriangle, CheckCircle, Server, Info, ShieldAlert, Cpu, Network, Moon, Sun, Download, FileText } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { jsPDF } from 'jspdf';
import { MetricPoint, IncidentReport, ThresholdConfig } from './types';
import { SettingsPanel } from './components/SettingsPanel';
import { RecentIncidents } from './components/RecentIncidents';
import { KpiCard } from './components/KpiCard';
import { ChartCard } from './components/ChartCard';
import { SimulationControls } from './components/SimulationControls';

export default function App() {
  const [data, setData] = useState<MetricPoint[]>([]);
  const [status, setStatus] = useState<'OK' | 'INCIDENT' | 'COOLDOWN'>('OK');
  const [incident, setIncident] = useState<IncidentReport | null>(null);

  // Settings & Thresholds
  const [thresholds, setThresholds] = useState<ThresholdConfig>({ latency: 1000, errorRate: 0.1 });
  const thresholdsRef = useRef(thresholds);
  useEffect(() => { thresholdsRef.current = thresholds; }, [thresholds]);

  // Simulation Controls & Fault Interceptors State
  const [isSimPlaying, setIsSimPlaying] = useState<boolean>(true);
  const [activeFault, setActiveFault] = useState<'none' | 'latency' | 'error' | 'both'>('none');
  const [trafficProfile, setTrafficProfile] = useState<'normal' | 'peak' | 'quiet'>('normal');

  const isSimPlayingRef = useRef(isSimPlaying);
  const activeFaultRef = useRef(activeFault);
  const trafficProfileRef = useRef(trafficProfile);
  const statusRef = useRef(status);

  useEffect(() => { isSimPlayingRef.current = isSimPlaying; }, [isSimPlaying]);
  useEffect(() => { activeFaultRef.current = activeFault; }, [activeFault]);
  useEffect(() => { trafficProfileRef.current = trafficProfile; }, [trafficProfile]);
  useEffect(() => { statusRef.current = status; }, [status]);

  const [lang, setLang] = useState<'en'|'fr'>('en');
  const t = {
    en: {
      title: "SRE-GPT Monitor",
      subtitle: "Autonomous Cloud Run Reliability Agent",
      statusLabel: "System Status",
      operational: "OPERATIONAL",
      incident: "INCIDENT DETECTED",
      cooldown: "MITIGATED (COOLDOWN)",
      latencyLabel: "Latency (avg)",
      errorLabel: "Error Rate",
      availLabel: "Availability",
      historyChart: "System Status History",
      aiReport: "Incident Post-Mortem Generated by Gemini",
      action: "Action",
      export: "JSON Export"
    },
    fr: {
      title: "SRE-GPT Moniteur",
      subtitle: "Agent Autonome de Fiabilité Cloud Run",
      statusLabel: "État du Système",
      operational: "OPÉRATIONNEL",
      incident: "INCIDENT DÉTECTÉ",
      cooldown: "RÉSOLU (COOLDOWN)",
      latencyLabel: "Latence (moyenne)",
      errorLabel: "Taux d'erreur",
      availLabel: "Disponibilité",
      historyChart: "Historique du Système",
      aiReport: "Rapport Post-Mortem Généré par Gemini",
      action: "Action",
      export: "Export JSON"
    }
  }[lang];

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
      
      if (e.key.toLowerCase() === 'd') {
        setIsDark(prev => !prev);
      } else if (e.key.toLowerCase() === 's') {
        e.preventDefault();
        document.getElementById('incident-search')?.focus();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  // Dark Mode State
  const [isDark, setIsDark] = useState(() => {
    if (typeof window !== 'undefined') {
      const local = localStorage.getItem('sre_theme');
      return local === 'dark' || (!local && window.matchMedia('(prefers-color-scheme: dark)').matches);
    }
    return false;
  });

  // Recent Incidents Store
  const [pastIncidents, setPastIncidents] = useState<IncidentReport[]>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('sre_recent_incidents');
      return saved ? JSON.parse(saved) : [];
    }
    return [];
  });

  useEffect(() => {
    localStorage.setItem('sre_recent_incidents', JSON.stringify(pastIncidents));
  }, [pastIncidents]);

  const addIncident = (inc: IncidentReport) => {
    setPastIncidents(prev => [inc, ...prev].filter((v,i,a) => a.findIndex(t => t.id === v.id) === i).slice(0, 5));
  };

  useEffect(() => {
    const root = window.document.documentElement;
    if (isDark) {
      root.classList.add('dark');
      localStorage.setItem('sre_theme', 'dark');
    } else {
      root.classList.remove('dark');
      localStorage.setItem('sre_theme', 'light');
    }
  }, [isDark]);

  // Simulation parameters & historical generation
  const consecutiveBreachesRef = useRef(0);
  const ticksSinceStatusChangeRef = useRef(0);

  useEffect(() => {
    const initialData: MetricPoint[] = Array.from({ length: 20 }).map((_, i) => {
      const d = new Date();
      d.setMinutes(d.getMinutes() - (20 - i));
      return {
        time: d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        latency_ms: 90 + Math.random() * 25,
        error_rate: Math.random() * 0.012,
        availability: 1.0,
        status_code: 0,
      };
    });
    
    setData(initialData);

    const interval = setInterval(() => {
      if (!isSimPlayingRef.current) return;

      // Calculate baseline load levels
      let baseLatency = 100;
      let baseError = 0.005;
      let availability = 1.0;

      if (trafficProfileRef.current === 'quiet') {
        baseLatency = 45 + Math.random() * 15;
        baseError = Math.random() * 0.004;
      } else if (trafficProfileRef.current === 'normal') {
        baseLatency = 95 + Math.random() * 25;
        baseError = Math.random() * 0.01;
      } else if (trafficProfileRef.current === 'peak') {
        baseLatency = 190 + Math.random() * 40;
        baseError = 0.015 + Math.random() * 0.015;
      }

      let latency_ms = baseLatency;
      let error_rate = baseError;
      const currentStatus = statusRef.current;
      const f = activeFaultRef.current;

      // Apply faulty overrides or incident state conditions
      if (f === 'latency' || (currentStatus === 'INCIDENT' && f !== 'error' && f !== 'both')) {
        latency_ms = 1150 + Math.random() * 250;
        error_rate = baseError + 0.012 + Math.random() * 0.012;
        availability = 0.985;
      } else if (f === 'error' || (currentStatus === 'INCIDENT' && f === 'error')) {
        latency_ms = baseLatency + 60 + Math.random() * 40;
        error_rate = 0.16 + Math.random() * 0.05;
        availability = 0.952;
      } else if (f === 'both' || (currentStatus === 'INCIDENT' && f === 'both')) {
        latency_ms = 1950 + Math.random() * 300;
        error_rate = 0.35 + Math.random() * 0.08;
        availability = 0.68 + Math.random() * 0.07;
      }

      // If resolving in Cooldown state, show gradual healing towards normal levels
      if (currentStatus === 'COOLDOWN') {
        latency_ms = baseLatency * 0.85 + 25 + Math.random() * 15;
        error_rate = baseError * 0.5 + Math.random() * 0.005;
        availability = 0.998;
      }

      // Read active slider alert thresholds
      const latencyThreshold = thresholdsRef.current.latency;
      const errorThreshold = thresholdsRef.current.errorRate;

      const isLatencyBreached = latency_ms > latencyThreshold;
      const isErrorBreached = error_rate > errorThreshold;
      const isBreaching = isLatencyBreached || isErrorBreached;

      let nextStatus = currentStatus;

      // Autonomous Protection Engine Transitions
      if (currentStatus === 'OK') {
        if (isBreaching) {
          consecutiveBreachesRef.current += 1;
          if (consecutiveBreachesRef.current >= 3) {
            nextStatus = 'INCIDENT';
            consecutiveBreachesRef.current = 0;
            ticksSinceStatusChangeRef.current = 0;

            // Formulate context-aware AI post mortem report
            let act = "Container Auto-Scaling Triggered (GCP Cloud Run)";
            let desc = `Anomaly Alert: Performance Degradation Detected.\n\n- Sub-nominal execution profile breached active protection policies.\n- Latency observed: ${Math.round(latency_ms)}ms (threshold: ${latencyThreshold}ms).\n- Error rate observed: ${(error_rate*100).toFixed(1)}% (threshold: ${(errorThreshold*100).toFixed(1)}%).\n\nRoot Cause: Resource starvation detected on primary cluster region under current traffic pattern.\nAction: AI Engine provisioned supplementary capacity and routed latency warming vectors.`;

            if (isLatencyBreached && !isErrorBreached) {
              act = "Horizontal Replication Scale Up (+4 Pods)";
              desc = `Anomaly Alert: Latency Threshold Breached.\n\n- Observed Latency: ${Math.round(latency_ms)}ms (alert ceiling: ${latencyThreshold}ms).\n- Active Database Socket allocation high.\n\nRoot Cause: Slow transactional locks query congestion on read-heavy DB tables.\nAction: Spanned additional active container instances to balance read replica allocation and flushed stale sockets.`;
            } else if (isErrorBreached && !isLatencyBreached) {
              act = "Automated Canary Rollback (Rev Stable v2.10.4)";
              desc = `Anomaly Alert: Error Spike Breached Safety Margins.\n\n- Simulated Error Rate: ${(error_rate*100).toFixed(1)}% (alert ceiling: ${(errorThreshold*100).toFixed(0)}%).\n\nRoot Cause: Missing runtime environment Variable causing downstream API authentication failure.\nAction: Autonomous engine successfully shifted 100% of user traffic backend connections to the previous fully-validated revision.`;
            } else if (f === 'both' || (isLatencyBreached && isErrorBreached)) {
              act = "Gateway Outage Protection Redirect (Cloud DNS Failover)";
              desc = `Anomaly Alert: Total Service Interruption Detected.\n\n- Critical Breach: Combined Latency (${Math.round(latency_ms)}ms) & Error Rate (${(error_rate*100).toFixed(1)}%) reached emergency ceiling.\n- Service availability dropped below SLA: ${(availability * 100).toFixed(1)}%.\n\nRoot Cause: Total backend microservice disconnect. Cascade connection failure.\nAction: Autonomous Agent engaged emergency DNS Failover and routed ingress requests to secondary multi-region standby environment.`;
            }

            const newInc: IncidentReport = {
              id: Date.now().toString(),
              timestamp: new Date().toISOString(),
              action: act,
              analysis: desc
            };

            setIncident(newInc);
            addIncident(newInc);
          }
        } else {
          consecutiveBreachesRef.current = 0;
        }
      } else if (currentStatus === 'INCIDENT') {
        ticksSinceStatusChangeRef.current += 1;
        if (ticksSinceStatusChangeRef.current >= 4) {
          nextStatus = 'COOLDOWN';
          ticksSinceStatusChangeRef.current = 0;
        }
      } else if (currentStatus === 'COOLDOWN') {
        ticksSinceStatusChangeRef.current += 1;
        if (ticksSinceStatusChangeRef.current >= 4) {
          nextStatus = 'OK';
          ticksSinceStatusChangeRef.current = 0;
          setIncident(null);
          setActiveFault('none');
        }
      }

      if (nextStatus !== currentStatus) {
        setStatus(nextStatus);
      }

      const statusCode = nextStatus === 'INCIDENT' ? 2 : nextStatus === 'COOLDOWN' ? 1 : 0;

      setData(prev => {
        const newData = [...prev.slice(1)];
        const now = new Date();
        const timeStr = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
        
        return [...newData, {
          time: timeStr,
          latency_ms,
          error_rate,
          availability,
          status_code: statusCode,
        }];
      });
    }, 2000);

    return () => clearInterval(interval);
  }, []);

  const currentMetrics = data[data.length - 1] || { latency_ms: 0, error_rate: 0, availability: 1 };
  const prevMetrics = data[data.length - 2];
  
  // Custom Recharts colors based on theme
  const axisColor = isDark ? '#9ca3af' : '#6b7280';
  const gridColor = isDark ? '#374151' : '#f3f4f6';
  const tooltipStyle = {
    backgroundColor: isDark ? '#1f2937' : '#ffffff',
    color: isDark ? '#f3f4f6' : '#111827',
    border: isDark ? '1px solid #374151' : 'none',
    borderRadius: '8px',
    boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' 
  };

  const downloadCurrentReport = () => {
    if (!incident) return;
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(incident, null, 2));
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", `incident_report_${new Date(incident.timestamp).getTime()}.json`);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
  };

  const downloadCurrentReportPDF = () => {
    if (!incident) return;
    const doc = new jsPDF();
    
    // Header band background (Dark Slate color)
    doc.setFillColor(31, 41, 55);
    doc.rect(0, 0, 210, 40, "F");
    
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.text("SRE-GPT Monitor - Incident Report", 14, 25);
    
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(156, 163, 175);
    doc.text("Autonomous Cloud Run Reliability Agent Core Post-Mortem", 14, 33);

    // Section header
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(31, 41, 55);
    doc.text("INCIDENT SUMMARY METADATA", 14, 54);
    
    // Decorative horizontal separator line
    doc.setDrawColor(229, 231, 235);
    doc.line(14, 57, 196, 57);
    
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(75, 85, 99);
    doc.text(`Incident ID: ${incident.id}`, 14, 65);
    doc.text(`Incident Date (UTC): ${new Date(incident.timestamp).toUTCString()}`, 14, 71);
    doc.text(`System Status: Remediation Successfully Completed / Cooldown Active`, 14, 77);
    doc.text(`SLA Impact Level: High (Service Availability Sub-Nominal)`, 14, 83);

    // Remediation box
    doc.setFillColor(239, 246, 255); // soft indigo backfill
    doc.rect(14, 90, 182, 22, "F");
    doc.setDrawColor(191, 219, 254);
    doc.rect(14, 90, 182, 22, "S");
    
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(29, 78, 216);
    doc.text("EXECUTED MITIGATION DISPATCHED:", 18, 97);
    
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(17, 24, 39);
    doc.text(incident.action, 18, 105);

    // Detailed Root Cause Analysis text section
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(31, 41, 55);
    doc.text("ROOT CAUSE & DETAILED CHRONOLOGY ANALYSIS", 14, 126);
    
    doc.setDrawColor(229, 231, 235);
    doc.line(14, 129, 196, 129);
    
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(55, 65, 81);
    
    const analysisWrapped = doc.splitTextToSize(incident.analysis, 182);
    doc.text(analysisWrapped, 14, 137);

    // Page decoration and automation disclaimer footer
    doc.setFont("Helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text("CONFIDENTIAL - SRE AUTOMATION ENGINE REPORT. FOR INTERNAL USE ONLY.", 14, 282);
    doc.text(`Page 1 of 1 • Generated at ${new Date().toLocaleString()}`, 142, 282);
    
    doc.save(`incident_report_postmortem_${incident.id}.pdf`);
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 text-gray-900 dark:text-gray-100 font-sans p-4 md:p-8 transition-colors duration-300 relative overflow-hidden">
      {/* Subtle Radial Gradient Overlays */}
      <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-indigo-500/10 dark:bg-indigo-500/5 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-10 right-1/4 w-[600px] h-[600px] bg-cyan-500/10 dark:bg-cyan-500/5 rounded-full blur-[140px] pointer-events-none" />
      <div className="absolute top-1/2 left-2/3 w-[450px] h-[450px] bg-purple-500/10 dark:bg-purple-500/5 rounded-full blur-[110px] pointer-events-none" />

      <div className="max-w-7xl mx-auto space-y-6 relative z-10">
        {/* Header */}
        <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white/5 dark:bg-gray-800/20 backdrop-blur-xl p-6 rounded-2xl border border-white/10 dark:border-gray-700/50 shadow-[0_4px_30px_rgba(0,0,0,0.1)] transition-colors">
          <div className="flex items-center gap-4">
            <div className="bg-blue-600 dark:bg-blue-500 p-3 rounded-xl text-white shadow-md">
              <Activity size={28} />
            </div>
            <div>
              <h1 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-gray-100">{t.title}</h1>
              <p className="text-sm text-gray-500 dark:text-gray-400 font-medium">{t.subtitle}</p>
            </div>
          </div>

          <div className="flex items-center gap-6">
            <div className="text-right">
              <div className="text-[10px] text-gray-500 dark:text-gray-400 font-semibold uppercase tracking-wider mb-1">{t.statusLabel}</div>
              <AnimatePresence mode="wait">
                {status === 'OK' && (
                  <motion.div key="ok" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.95 }} className="flex items-center justify-end gap-2 text-emerald-700 dark:text-emerald-400 font-bold bg-emerald-50 dark:bg-emerald-500/10 px-4 py-2 rounded-lg border border-emerald-100 dark:border-emerald-500/20">
                    <CheckCircle size={18} />
                    <span>{t.operational}</span>
                  </motion.div>
                )}
                {status === 'INCIDENT' && (
                  <motion.div key="incident" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.95 }} className="flex items-center justify-end gap-2 text-red-700 dark:text-red-400 font-bold bg-red-50 dark:bg-red-500/10 px-4 py-2 rounded-lg border border-red-200 dark:border-red-500/20 shadow-sm">
                    <AlertTriangle size={18} className="animate-pulse" />
                    <span>{t.incident}</span>
                  </motion.div>
                )}
                {status === 'COOLDOWN' && (
                  <motion.div key="cooldown" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.95 }} className="flex items-center justify-end gap-2 text-amber-700 dark:text-amber-400 font-bold bg-amber-50 dark:bg-amber-500/10 px-4 py-2 rounded-lg border border-amber-200 dark:border-amber-500/20">
                    <ShieldAlert size={18} />
                    <span>{t.cooldown}</span>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
            
            <button
              onClick={() => setLang(l => l === 'en' ? 'fr' : 'en')}
              className="px-3 py-1.5 rounded-xl font-bold bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors uppercase text-sm"
              title="Toggle Language"
            >
              {lang}
            </button>
            <button 
              onClick={() => setIsDark(!isDark)} 
              className="p-3 rounded-xl bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
              title="Toggle Theme"
            >
              {isDark ? <Sun size={20} /> : <Moon size={20} />}
            </button>
          </div>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          <div className="lg:col-span-3 space-y-6">
            {/* KPIs */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <KpiCard 
                title={t.latencyLabel} 
                value={`${Math.round(currentMetrics.latency_ms)} ms`}
                prevValue={prevMetrics ? `${Math.round(prevMetrics.latency_ms)} ms` : undefined}
                lowerIsBetter={true}
                icon={<Network size={20} />}
                status={currentMetrics.latency_ms > thresholds.latency ? 'danger' : 'normal'}
              />
              <KpiCard 
                title={t.errorLabel} 
                value={`${(currentMetrics.error_rate * 100).toFixed(1)}%`}
                prevValue={prevMetrics ? `${(prevMetrics.error_rate * 100).toFixed(1)}%` : undefined}
                lowerIsBetter={true}
                icon={<Server size={20} />}
                status={currentMetrics.error_rate > thresholds.errorRate ? 'danger' : 'normal'}
              />
              <KpiCard 
                title={t.availLabel} 
                value={`${(currentMetrics.availability * 100).toFixed(1)}%`}
                prevValue={prevMetrics ? `${(prevMetrics.availability * 100).toFixed(1)}%` : undefined}
                lowerIsBetter={false}
                icon={<Cpu size={20} />}
                status={currentMetrics.availability < 0.95 ? 'danger' : 'normal'}
              />
            </div>

            {/* Charts */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <ChartCard title="API Latency (ms)">
                <ResponsiveContainer width="100%" height={260}>
                  <AreaChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <defs>
                      <linearGradient id="colorLat" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor={currentMetrics.latency_ms > thresholds.latency ? '#ef4444' : '#3b82f6'} stopOpacity={0.4}/>
                        <stop offset="95%" stopColor={currentMetrics.latency_ms > thresholds.latency ? '#ef4444' : '#3b82f6'} stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={gridColor} />
                    <XAxis dataKey="time" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: axisColor }} minTickGap={30} />
                    <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: axisColor }} />
                    <Tooltip contentStyle={tooltipStyle} />
                    <Area 
                      type="monotone" 
                      dataKey="latency_ms" 
                      stroke={currentMetrics.latency_ms > thresholds.latency ? '#ef4444' : '#3b82f6'} 
                      strokeWidth={3}
                      fillOpacity={1} 
                      fill="url(#colorLat)" 
                      isAnimationActive={false}
                    />
                  </AreaChart>
                </ResponsiveContainer>
              </ChartCard>

              <ChartCard title="Error Rate (%)">
                <ResponsiveContainer width="100%" height={260}>
                  <LineChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={gridColor} />
                    <XAxis dataKey="time" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: axisColor }} minTickGap={30} />
                    <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: axisColor }} tickFormatter={(tick) => `${(tick * 100).toFixed(0)}%`} />
                    <Tooltip 
                      formatter={(value: number) => [`${(value * 100).toFixed(2)}%`, 'Error Rate']}
                      contentStyle={tooltipStyle}
                    />
                    <Line 
                      type="stepAfter" 
                      dataKey="error_rate" 
                      stroke={currentMetrics.error_rate > thresholds.errorRate ? '#ef4444' : '#8b5cf6'} 
                      strokeWidth={3} 
                      dot={false}
                      isAnimationActive={false}
                    />
                  </LineChart>
                </ResponsiveContainer>
              </ChartCard>
            </div>

            <ChartCard title={t.historyChart}>
              <ResponsiveContainer width="100%" height={200}>
                <AreaChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                  <defs>
                    <linearGradient id="colorStatus" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#8b5cf6" stopOpacity={0.4}/>
                      <stop offset="95%" stopColor="#8b5cf6" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={gridColor} />
                  <XAxis dataKey="time" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: axisColor }} minTickGap={30} />
                  <YAxis 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{ fontSize: 10, fill: axisColor }} 
                    domain={[0, 2]} 
                    ticks={[0, 1, 2]} 
                    tickFormatter={(tick) => tick === 2 ? 'INCIDENT' : tick === 1 ? 'COOLDOWN' : 'OK'} 
                  />
                  <Tooltip 
                    formatter={(value: number) => [value === 2 ? 'INCIDENT' : value === 1 ? 'COOLDOWN' : 'OK', 'System Status']}
                    contentStyle={tooltipStyle}
                  />
                  <Area 
                    type="stepAfter" 
                    dataKey="status_code" 
                    stroke="#8b5cf6" 
                    strokeWidth={3}
                    fillOpacity={1} 
                    fill="url(#colorStatus)" 
                    isAnimationActive={false}
                  />
                </AreaChart>
              </ResponsiveContainer>
            </ChartCard>

            {/* AI Report Section */}
            <AnimatePresence>
              {incident && (
                <motion.div 
                  initial={{ opacity: 0, height: 0, scale: 0.98 }} 
                  animate={{ opacity: 1, height: 'auto', scale: 1 }} 
                  exit={{ opacity: 0, height: 0, scale: 0.98 }}
                  className="bg-white/5 dark:bg-gray-800/20 backdrop-blur-xl border border-white/10 dark:border-gray-700/50 shadow-[0_4px_30px_rgba(0,0,0,0.1)] rounded-2xl overflow-hidden transform-gpu"
                >
                  <div className="bg-indigo-500/5 dark:bg-indigo-950/10 p-5 px-6 border-b border-white/10 dark:border-gray-700/30 flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                    <div className="flex items-start gap-4">
                      <div className="bg-white/5 dark:bg-gray-800/40 p-2.5 shadow-sm rounded-full text-indigo-600 dark:text-indigo-400 mt-1 shrink-0">
                        <Info size={22} />
                      </div>
                      <div className="flex-1">
                        <h3 className="text-xl font-bold text-indigo-950 dark:text-indigo-100 mb-1.5">{t.aiReport}</h3>
                        <div className="flex flex-wrap items-center gap-2 text-sm text-indigo-600 dark:text-indigo-400 font-medium">
                          <span className="bg-indigo-100/10 dark:bg-indigo-500/30 px-2.5 py-1 rounded-md text-indigo-700 dark:text-indigo-300">{t.action}: {incident.action}</span>
                          <span className="hidden sm:inline opacity-60">•</span>
                          <span className="opacity-80">{new Date(incident.timestamp).toLocaleTimeString()}</span>
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-wrap items-center gap-2 self-start sm:self-auto">
                      <button 
                        onClick={downloadCurrentReport}
                        className="flex items-center gap-2 whitespace-nowrap px-4 py-2 text-sm font-bold bg-white/5 dark:bg-gray-800/10 text-indigo-700 dark:text-indigo-400 border border-white/10 dark:border-gray-700/30 rounded-lg shadow-sm hover:bg-indigo-50/15 dark:hover:bg-indigo-500/10 transition-colors cursor-pointer"
                        title="Download JSON Report"
                      >
                        <Download size={16} /> {t.export}
                      </button>
                      <button 
                        onClick={downloadCurrentReportPDF}
                        className="flex items-center gap-2 whitespace-nowrap px-4 py-2 text-sm font-bold bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-500 dark:hover:bg-indigo-600 text-white rounded-lg shadow-sm transition-colors cursor-pointer"
                        title="Download PDF Document"
                      >
                        <FileText size={16} /> {lang === 'en' ? 'Download PDF' : 'Télécharger PDF'}
                      </button>
                    </div>
                  </div>
                  <div className="p-6 px-8 bg-transparent">
                    <div className="prose prose-indigo dark:prose-invert max-w-none text-gray-700 dark:text-gray-300 font-medium whitespace-pre-line text-[15px] leading-relaxed">
                      {incident.analysis}
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          <div className="space-y-6">
            <SimulationControls 
              isSimPlaying={isSimPlaying}
              onToggleSim={() => setIsSimPlaying(!isSimPlaying)}
              activeFault={activeFault}
              onInjectFault={(fault) => {
                setActiveFault(fault);
                if (fault === 'none' && status === 'INCIDENT') {
                  setStatus('COOLDOWN');
                }
              }}
              trafficProfile={trafficProfile}
              onChangeProfile={setTrafficProfile}
              lang={lang}
            />
            <SettingsPanel thresholds={thresholds} onThresholdChange={setThresholds} />
            <RecentIncidents incidents={pastIncidents} />
          </div>
        </div>

        {/* Footer Helper Hints */}
        <footer className="mt-12 pt-6 border-t border-gray-200/20 dark:border-gray-800/50 flex flex-col sm:flex-row justify-between items-center gap-4 text-xs text-gray-500 dark:text-gray-400">
          <div>
            System Status: <span className="text-emerald-500 font-semibold">• ONLINE</span>
          </div>
          <div className="flex flex-wrap items-center gap-4">
            <span>Keyboard Shortcuts:</span>
            <span className="flex items-center gap-1.5 bg-white/5 px-2 py-0.5 rounded border border-white/10 dark:border-gray-800 font-mono shadow-sm">
              <kbd className="font-sans font-bold text-indigo-500 dark:text-indigo-400">D</kbd> {lang === 'en' ? 'Toggle Theme' : 'Mode Sombre'}
            </span>
            <span className="flex items-center gap-1.5 bg-white/5 px-2 py-0.5 rounded border border-white/10 dark:border-gray-800 font-mono shadow-sm">
              <kbd className="font-sans font-bold text-indigo-500 dark:text-indigo-400">S</kbd> {lang === 'en' ? 'Search Incidents' : 'Rechercher Incidents'}
            </span>
          </div>
        </footer>

      </div>
    </div>
  );
}
